version: '3'
services:
  dump1090-fa:
    image: dump1090-fa
    devices:
      - "/dev/bus/usb"
    expose:
      - "30001"
      - "30002"
      - "30003"
      - "30004"
      - "30005"
      - "30104"
      - "8080"
    ports:
      - "8082:8080"
    environment:
      - LAT=<insert lat here>
      - LON=<insert lon here>
  piaware:
    image: piaware
    environment:
      - FLIGHTAWARE_USER=<insert username here>
      - FLIGHTAWARE_PASSWORD=<insert password here>
  fr24feed:
    image: fr24feed
    environment:
      - FR24_KEY=<insert fr24 key here>
